Class {
	#name : #CPPSFileAnchor,
	#superclass : #CPPSSourceAnchor,
	#traits : 'FamixTFileAnchor + FamixTFileNavigation',
	#classTraits : 'FamixTFileAnchor classTrait + FamixTFileNavigation classTrait',
	#category : #'CPPS-Entities-Entities'
}

{ #category : #meta }
CPPSFileAnchor class >> annotation [

	<FMClass: #FileAnchor super: #CPPSSourceAnchor>
	<package: #'CPPS-Entities'>
	<generated>
	^self
]
