"
A MooseProjectDirectoryPersistanceManagerFake is a fake object to test MooseProjectDirectoryPersistanceManager without saving it on the disk.

"
Class {
	#name : #MooseProjectDirectoryPersistanceManagerFake,
	#superclass : #MooseProjectDirectoryPersistanceManager,
	#category : #'Moose-ProjectHolder-Tests'
}

{ #category : #persistance }
MooseProjectDirectoryPersistanceManagerFake >> saveMooseProjectObject [
	"do nothing"
]
